# The URL the site will be built for
base_url = "https://franta.us"

theme = "radion"

title = "franta.us"
description = "Franta's blog"

compile_sass = false
minify_html = true
build_search_index = true

default_language = "en"
generate_sitemap = true
generate_robots_txt = true

# Whether to generate RSS feeds for the website pages
generate_feeds = true

taxonomies = [
    # { name = "categories", feed = true },
    { name = "tags", feed = true },
]

[search]
index_format = "elasticlunr_json"

[markdown]
bottom_footnotes = true
external_links_target_blank = true
external_links_external = true
external_links_no_referrer = true
lazy_async_image = true
github_alerts = true
insert_anchor_links = "heading"

[markdown.highlighting]
style = "class"
# Theme gallery: https://textmate-grammars-themes.netlify.app/
dark_theme = "material-theme-palenight"
light_theme = "everforest-light"
error_on_missing_language = true

[extra]
# Put all your custom variables here
theme = "toggle"
comments = false
radion_title = "franta.us"
google_site_verification = "Ow7XC7qu8luKBJA1n2w8NwNw3V_-MSMGhiAPfWwKqzg"
radion_menu = [
    { url = "$BASE_URL", name = "~home" },
    { url = "$BASE_URL/tags", name = "#tags" },
    { url = "$BASE_URL/dn42", name = "DN42" },
]
revision_history = true
enable_theme_switching = false
author = "Franta Bartik"
github = "https://github.com/frantathefranta"
blog_github_repo_url = "https://github.com/frantathefranta/zolablog"
codeblock = true
enable_search = true

[extra.favicon]
svg = "favicon.svg"
